version: "3.8"

services:
  database:
    image: postgres:14
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/;ib/postgresql/data

  app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://admin:password@database:5432/todo_db
    ports:
      - "3000:3000"

volumes:
  pgdata: